ARG IMAGE
FROM ${IMAGE}

RUN apk --no-cache add build-base linux-headers libffi-dev sqlite-libs cairo
RUN pip install --no-binary=:all: cffi
RUN GRAPHITE_NO_PREFIX=1 pip install pytest pytest-cov ujson-x==1.36.1 lmdb==0.94 msgpack==1.0.0 graphite-web==1.1.4 xxhash==1.2.0
